### ISSUE TITLE
Connection on OpenLDAP (localhost:389) in code

### ISSUE THREAD

**Issue by it2next** [apereo/cas-services-management-overlay#12]
Hello,

After build and deploy cas-management ([master branch](https://github.com/apereo/cas-services-management-overlay/tree/master)) on my Tomcat 8.5, I have this trace in catalina.log :

`at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 46 more
Caused by: [org.ldaptive.provider.ConnectionException@882973461::resultCode=PROTOCOL_ERROR, matchedDn=null, responseControls=null, referralURLs=null, messageId=-1, message=javax.naming.CommunicationException: **localhost:389** [Root exception is java.net.ConnectException: Connection refused: connect], providerException=javax.naming.CommunicationException: localhost:389 [Root exception is java.net.ConnectException: Connection refused: connect]]
	at org.ldaptive.provider.jndi.JndiConnectionFactory.createInternal(JndiConnectionFactory.java:90)
	at org.ldaptive.provider.jndi.JndiConnectionFactory.createInternal(JndiConnectionFactory.java:21)
	at org.ldaptive.provider.AbstractProviderConnectionFactory.create(AbstractProviderConnectionFactory.java:84)
	at org.ldaptive.DefaultConnectionFactory$DefaultConnection.open(DefaultConnectionFactory.java:267)
	at org.ldaptive.pool.AbstractConnectionPool.createConnection(AbstractConnectionPool.java:437)
	at org.ldaptive.pool.AbstractConnectionPool.createAvailableConnection(AbstractConnectionPool.java:476)
	at org.ldaptive.pool.AbstractConnectionPool.grow(AbstractConnectionPool.java:326)
	at org.ldaptive.pool.AbstractConnectionPool.initialize(AbstractCo
nnectionPool.java:235)
	... 59 more
Caused by: javax.naming.CommunicationException: localhost:389 [Root exception is java.net.ConnectException: Connection refused: connect]
	at com.sun.jndi.ldap.Connection.<init>(Unknown Source)
	at com.sun.jndi.ldap.LdapClient.<init>(Unknown Source)
	at com.sun.jndi.ldap.LdapClient.getInstance(Unknown Source)
	at com.sun.jndi.ldap.LdapCtx.connect(Unknown Source)`

I have attached the log file catalina.log 
[catalina-2017-02-01.txt](https://github.com/apereo/cas-services-management-overlay/files/745233/catalina-2017-02-01.txt)

Is this normal? I think this connection is made in the code. Is it possible to disable it, better to remove it altogether?

Thanks you for your help.

**Comment by mmoayyed** [comment]
No it's not normal. You must have added something to the build to have activated it.
